aws_access_key="<access key for aws>"
aws_secret_key="<secret access key for aws>"
vpc_id="<existing vpc id>"
subnet_id="<existing subnet id>"
instance_type="t3.medium"
aws_public_key_name="<name of public key which will be created>"
